declare module 'element-plus'
declare module 'element-plus/es/locale/lang/zh-cn'
declare module 'element-plus/es/locale/lang/zh-tw'
declare module 'element-plus/es/locale/lang/en'
declare module 'pinia-plugin-persist'
